# Generated by Django 6.0.7 on 2026-07-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(help_text='e.g. PAGE_VIEW, ADD_TO_CART, REMOVE_FROM_CART, APPLY_COUPON, CHECKOUT_SUBMIT', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Coupon code e.g. WELCOME10', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED', 'Fixed Amount Discount')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10 for 10%) or fixed amount (e.g. 50 for ₹50)', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Minimum subtotal required to use this coupon', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('items', models.JSONField(help_text='JSON representation of cart items')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(help_text='Unique product slug e.g. health-mix-300g', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inr_price', models.CharField(blank=True, help_text='e.g. ₹110. Leave blank to generate automatically from price.', max_length=50)),
                ('image', models.CharField(default='refence image/image.png', help_text='Image file path relative to root or full URL', max_length=255)),
                ('badge', models.CharField(blank=True, help_text='e.g. Flagship Pouch, Family Pack', max_length=100, null=True)),
                ('tag', models.CharField(help_text='e.g. Starter, Family, Premium', max_length=100)),
                ('details_badge', models.CharField(blank=True, help_text='e.g. Sprouted Millets & Grains', max_length=200)),
                ('lead', models.TextField(blank=True, help_text='Short leading description on detail page')),
                ('ingredients', models.TextField(blank=True, help_text='Ingredients list')),
                ('about', models.TextField(blank=True, help_text='Detailed about section')),
                ('is_active', models.BooleanField(default=True)),
                ('order_weight', models.IntegerField(default=0, help_text='Ordering weight for list rendering (lower is first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_whatsapp_number', models.CharField(default='919876543210', help_text='WhatsApp number of the owner (include country code, e.g. 919876543210 for India)', max_length=50)),
                ('openwa_api_url', models.URLField(default='http://localhost:2785', help_text='Base URL of the OpenWA Gateway', max_length=255)),
                ('openwa_api_key', models.CharField(blank=True, help_text='API key for OpenWA authorization (if any)', max_length=255, null=True)),
                ('openwa_session_id', models.CharField(default='default', help_text='Active WhatsApp session ID on the gateway', max_length=100)),
                ('announcement_text', models.CharField(default='FREE SHIPPING ON ORDERS OVER ₹999 / $40 • SAVE 10% ON SUBSCRIPTIONS', max_length=255)),
                ('logo_title', models.CharField(default='MANGALAM', max_length=100)),
                ('logo_subtitle', models.CharField(default='HEALTHY FOODS', max_length=100)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=999.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
