# Generated by Django 6.0.7 on 2026-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading shown on the banner', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_upload', models.ImageField(blank=True, help_text='Banner image (auto-converted to WebP)', null=True, upload_to='banners/')),
                ('badge', models.CharField(blank=True, help_text='Small eyebrow/badge text', max_length=120)),
                ('cta_text', models.CharField(blank=True, help_text="Button label e.g. 'Shop the mix'", max_length=80)),
                ('cta_page', models.CharField(blank=True, help_text='Frontend page key e.g. shop, science, about', max_length=80)),
                ('placement', models.CharField(choices=[('hero', 'Hero deck'), ('promo', 'Promo strip'), ('popup', 'Popup')], default='hero', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('order_weight', models.IntegerField(default=0, help_text='Lower shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_weight', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Upload a product image (auto-converted to WebP). Overrides the legacy path above.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='refence image/image.png', help_text='Legacy image path. Prefer uploading via the Image field below.', max_length=255),
        ),
    ]
