# Generated by Django 6.0.7 on 2026-07-11 08:11

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_banner_product_image_upload_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Banner image (auto-converted to WebP)', null=True, upload_to='banners/', validators=[api.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Upload a product image (auto-converted to WebP). Overrides the legacy path above.', null=True, upload_to='products/', validators=[api.validators.validate_image_upload]),
        ),
    ]
