# Generated by Django 6.0.7 on 2026-07-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_banner_image_upload_alter_product_image_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(help_text='Page URL that was audited', max_length=500)),
                ('score', models.IntegerField(default=0, help_text='0–100 on-page SEO score')),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('counts', models.JSONField(blank=True, default=dict, help_text='{pass, warn, fail}')),
                ('results', models.JSONField(blank=True, default=list, help_text='Per-check results')),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SEO Audit',
                'ordering': ['-created_at'],
            },
        ),
    ]
