import json
import requests
import logging

logger = logging.getLogger(__name__)

def send_whatsapp_order_notification(order, site_config):
    """
    Sends a WhatsApp message to the owner containing the details of the new order
    using the OpenWA Gateway REST API.
    """
    if not site_config.owner_whatsapp_number:
        logger.warning("WhatsApp notification skipped: Owner number not set in SiteConfig.")
        return False, "Owner number not set in SiteConfig."

    url = f"{site_config.openwa_api_url.rstrip('/')}/api/sessions/{site_config.openwa_session_id}/messages/send-text"
    
    # Format phone number. Remove any leading '+' or space, ensure it ends with '@c.us'
    clean_number = "".join(filter(str.isdigit, site_config.owner_whatsapp_number))
    if not clean_number.endswith("@c.us"):
        to_number = f"{clean_number}@c.us"
    else:
        to_number = clean_number

    # Compile order details text
    items_list = []
    # items is expected to be a list of dicts: [{'name': '...', 'quantity': 1, 'price': 100, 'option': 'one-time'}]
    items_data = order.items
    if isinstance(items_data, str):
        try:
            items_data = json.loads(items_data)
        except Exception:
            pass

    if isinstance(items_data, list):
        for idx, item in enumerate(items_data, 1):
            items_list.append(
                f"{idx}. {item.get('name')} x{item.get('quantity')} ({item.get('option', 'one-time')}) - ₹{item.get('price')}"
            )
    else:
        items_list.append(str(items_data))

    items_text = "\n".join(items_list)

    message_text = (
        f"🚨 *NEW MANGALAM HEALTHY FOODS ORDER!*\n\n"
        f"👤 *Customer:* {order.name}\n"
        f"📞 *Mobile:* {order.mobile}\n"
        f"📍 *Address:* {order.address}\n\n"
        f"🛒 *Items Ordered:*\n{items_text}\n\n"
        f"💵 *Subtotal:* ₹{order.subtotal}\n"
        f"🏷️ *Coupon:* {order.coupon_code or 'None'}\n"
        f"📉 *Discount:* ₹{order.discount}\n"
        f"💰 *Total Amount:* ₹{order.total}\n\n"
        f"📅 *Date:* {order.created_at.strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"--- Generated by Django Backend ---"
    )

    headers = {
        "Content-Type": "application/json"
    }
    if site_config.openwa_api_key:
        headers["X-API-Key"] = site_config.openwa_api_key

    payload = {
        "chatId": to_number,
        "text": message_text
    }

    try:
        logger.info(f"Attempting to send WhatsApp message to {to_number} via OpenWA: {url}")
        response = requests.post(url, json=payload, headers=headers, timeout=10)
        
        if response.status_code in [200, 201]:
            logger.info("WhatsApp message sent successfully via OpenWA.")
            return True, None
        else:
            err_msg = f"OpenWA server returned status {response.status_code}: {response.text}"
            logger.error(err_msg)
            return False, err_msg
            
    except requests.exceptions.RequestException as e:
        err_msg = f"Network error connecting to OpenWA: {str(e)}"
        logger.error(err_msg)
        return False, err_msg
