services:
  db:
    image: mysql:8.0
    container_name: healthmix_db
    restart: always
    environment:
      MYSQL_DATABASE: health_mix
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: healthmix_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_NAME=HealthMixApi
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=health_mix
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: healthmix_frontend
    restart: always
    ports:
      - "5180:5180"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
